spring.application.name=news_paper

spring.datasource.url=jdbc:mysql://localhost:3306/news_paper
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

supabase.url=https://qtickunizsfzcegifkno.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0aWNrdW5penNmemNlZ2lma25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MjAxMTQsImV4cCI6MjA3OTE5NjExNH0.3PHJzzhrML4AgGD3hEp3o_b7OAAn4iJcfRHj_BgfK7c
supabase.bucket=/storage/v1/object/bucket_1/
supabase.image=/storage/v1/object/public/bucket_1/


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=005f60dabcc8f8
spring.mail.password=c6085577043765
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
